### PR TITLE
Parallel cucumbers

### LINKED ISSUE #7307: CI runs up from 0:45h to 4:30h
# Issue

CI runs now take ~4:30h to run. Before #7180 they took only ~0:45h.

# Steps to reproduce

Push anything that starts a CI run.

# Specifications

Please provide details of your development environment.
- CI for osrm-backend on github

### PR DESCRIPTION
**Pull request by MarcelloPerathoner**
# Issue

Fixes #7307 - CI runs up from 0:45h to 4:30h

## Improvements

Parallel execution of cucumber tests tremendously improves running times.

Note: when using `--parallel N` make sure there are `N` contiguous free ports at the
configured port number (eg. at ports 5000--5000+N).

A lot more can be configured with profiles (in `cucumber.mjs`). Usage examples:

``` bash
$ npx cucumber-js -p home -p ch -p mmap --format html:/tmp/testlog.html --parallel 8
$ npx cucumber-js -p github -p mld -p directly --parallel 8
$ npm test -- --parallel $JOBS --fail-fast
```
Github step summaries display the test results:

Screenshot 2026-01-08 at 21-33-21 WIP Parallel cucumbers · Project-OSRM_osrm-backend@6b55220

On github CI full logs, also containing the outputs from all binaries, are published to
`https://reports.cucumber.io/`.

Code refactored and simplified. ~150 LoC less.

### Other Fixes

During development other problems were found and fixed:

- The *datastore* load method now works as expected: one and the same `osrm-routed` will
be running in the background for the whole duration of the test. Previous behaviour: for
each scenario an `osrm-routed` would be spawned, loaded with datastore, and then killed
again.

- The data watchdog in `osrm-routed` now will emit the message: 'updated facade' right
after the update (previous behaviour: right before the update), so that it can be used
for process synchronization.

## Breaking changes

If you run the tests using the `npx cucumber-js ...` calling method you must add either
`-p home` or `-p github` as the first profile, eg.:

``` bash
$ npx cucumber-js -p home -p mld -p mmap --parallel 8
```
instead of:

``` bash
$ OSRM_LOAD_METHOD=mmap npx cucumber-js -p mld
```

Old cached files are not cleaned automatically anymore because that interfered with
concurrency. There is no hook in cucumber that runs before the workers start.

We don't support changing the load method in mid-run anymore. (eg. "Given data is loaded
with datastore" no longer works). Reason: With the datastore load method an
`osrm-routed` will be constantly running in the background. No second `osrm-routed` can
open the same port again.

### Retired Environment Variables

- `OSRM_CONNECTION_RETRIES`
- `OSRM_CONNECTION_EXP_BACKOFF_COEF`

## Other changes

Removed one cache level. CH and MLD are processed and cached separately.

The outputs of osrm binaries are not written into lots of small files anymore. Instead
use the `--format html:test/logs/testlog.html` commandline argument to get one big HTML
file with all outputs embedded.

## New configuration variables

New environment variables and/or cucumber `worldParameters` entries were introduced. The
whole configuration is done in `cucumber.mjs`.

| Environment Variable     | worldParameters | Defaults to  |                          |
| ------------------------ | --------------- | ------------ | ------------------------ |
| `CUCUMBER_TIMEOUT`       | `timeout`       | 5000         |  Scenario timeout in ms. |
| `CUCUMBER_HTTP_TIMEOUT`  | `httpTimeout`   | 2000         |  HTTP timeout in ms.     |
| `CUCUMBER_TEST_PATH`     | `testPath`      | `test`       |  The test directory      |
| `CUCUMBER_PROFILES_PATH` | `profilesPath`  | `profiles`   |  The profiles directory  |
| `CUCUMBER_LOGS_PATH`     | `logsPath`      | `test/logs`  |  The logs directory      |
| `CUCUMBER_CACHE_PATH`    | `cachePath`     | `test/cache` |  The cache directory     |
| `OSRM_BUILD_DIR`         | `buildPath`     | `build`      |  Path to the binaries    |
| `OSRM_LOAD_METHOD`       | `loadMethod`    | datastore    |  Data load method        |
| `OSRM_ALGORITHM`         | `algorithm`     | ch           |  Routing algorithm       |
| `OSRM_IP`                | `ip`            | 127.0.0.1    |  IP Address              |
| `OSRM_PORT`              | `port`          | 5000         |  IP Port                 |

## New tags

| Tag                                 | A scenario thus tagged ...                                   |
| ----------------------------------- | ------------------------------------------------------------ |
| `@isolated`                         | will not run while any other scenario is running in parallel |
| `@with_(datastore\|directly\|mmap)` | will be executed iff the load method matches                 |
| `@no_(datastore\|directly\|mmap)`   | will be executed unless the load method matches              |
| `@with_(ci\|mld)`                   | will be executed iff the algorithm matches                   |
| `@no_(ci\|mld)`                     | will be executed unless the algorithm matches                |

## Tasklist

 - [X] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))
 - [X] TODO: clean up and remove some unrelated stuff
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [ ] review
 - [ ] adjust for comments

## Requirements / Relations

Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by afarber** [comment]
Thanks for working on speeding up the CI! The parallel cucumber approach looks promising.

One concern: could we keep the CI matrix changes out of this PR? Switching from macos-13 to macos-15-intel drops test coverage for users on Ventura/Sonoma, and adding clang-20 (which isn't released yet) seems unrelated to the parallelization work. These changes could be discussed separately if there's a reason to drop older platform support.

Also spotted a few bugs in osrm_loader.js - there are references to an undefined err variable in the error handlers (lines 45, 118, 132) that would crash if osrm-routed fails.

**Comment by MarcelloPerathoner** [comment]
The PR is still WIP. I will cleanup before releasing it. 

BTW clang-21 is current. The reason to drop macos-13 is that github does not support it anymore.

File: features/lib/osrm_loader.js [hunk 1]
```diff
@@ -1,310 +1,247 @@
...
-      if (err) return callback(err);
-      if (!this.osrmIsRunning()) this.launch(callback);
-      else {
-        this.scope.setupOutputLog(
-          this.child,
-          fs.createWriteStream(this.scope.scenarioLogFile, { flags: 'a' }),
-        );
-        callback();
+    });
+    // process.on('SIGIO', this.resolve);
```
Comment (TheMarex) [inline features/lib/osrm_loader.js]: Left-over?

**Comment by TheMarex** [comment]
Do you think the non-cucumber changes (datastore, routed, etc) can be broken out independently without messing with the tests? It is always quite the challenge to review large changes like this so I would appreciate the extra effort if possible. :pray:

**Comment by MarcelloPerathoner** [comment]
The shared memory changes could easily go elsewhere, as they are not the primary reason for sync loss between the test suite and routed. But the change in routed is critical (and trivial too).

The changes to the github workflow should go elsewhere. I'm just playing around to get windows to run the test suite too. See if any surprises come up.

**Comment by MarcelloPerathoner** [comment]
Ready for review. I have removed everything that is not strictly necessary. The shared memory fixes for macOS and Windows will go into another PR. Until that macOS tests with datastore will be flaky.

File: features/support/env.js [hunk 2]
```diff
@@ -1,85 +1,78 @@
...
-import path from 'path';
-import util from 'util';
-import fs from 'fs';
-import d3 from 'd3-queue';
-import child_process from 'child_process';
-import tryConnect from '../lib/try_connect.js';
-import { setDefaultTimeout } from '@cucumber/cucumber';
-
-// Set global timeout for all steps and hooks
-setDefaultTimeout(
```
Comment (afarber) [inline features/support/env.js:11]: You have removed the setDefaultTimeout() method and that is why the `CUCUMBER_TIMEOUT: 60000` from the `conan-macos-arm64-release-node` section is not passed anywhere and default timeout of 5000 is used causing the macOS arm64 job to fail

File: docs/cucumber.md [hunk 3]
```diff
@@ -0,0 +1,144 @@
...
+located by default in `test/cache` and should be cleaned periodically:
+
+``` bash
+$ rm -rf test/cache
+```
+
+## Configuration
+
+The whole configuration is done in `cucumber.mjs`. You can either edit `worldParameters`
+in `cucumber.mjs` or use environemnt variables to override single defaults.
```
Comment (afarber) [inline docs/cucumber.md]: Typo: environemnt

File: features/support/cache.js [hunk 4]
```diff
@@ -1,187 +1,39 @@
...
+    // shorten uri to be relative to 'features/'
+    const featurePath = path.relative(path.resolve('./features'), uri);
+    /** eg. car/access.feature/{hash}/ */
+    this.featureID = path.join(featurePath, hexHash);
+    /** eg. test/cache/car/access.feature/{hash}/ */
+    this.featureCacheDirectory = path.join(this.env.wp.cachePath, this.featureID);
+
+    // ensure there is a make a cache directory
+    fs.mkdirSync(this.featureCacheDirectory, { recursive: true });
+  };
```
Comment (afarber) [inline features/support/cache.js]: The semicolon is not needed

File: features/lib/osrm_loader.js [hunk 5]
```diff
@@ -1,310 +1,246 @@
...
+  async logSync(msg) {
+    if (this.current_scenario)
+      await this.current_scenario.log(msg);
+    else
+      env.globalLog(msg);
+  }
+
+  before(scenario) {
+    this.current_scenario = scenario;
+    this.semaphore = new Promise((resolve) => this.resolve = resolve);
```
Comment (afarber) [inline features/lib/osrm_loader.js:152]: Consider adding a timeout fallback:

```js
  before(scenario) {
    this.current_scenario = scenario;
    this.semaphore = new Promise((resolve, reject) => {
      this.resolve = resolve;
      setTimeout(() => reject(new Error('Timed out waiting for facade update')), env.wp.timeout);
    });
    // ...
 }
```

Or use `Promise.race()` with the existing `waitForConnection()` timeout.

Comment (MarcelloPerathoner) [reply features/lib/osrm_loader.js:152]: In that case Cucumber will timeout. No need to complicate the code.

File: features/support/env.js (hunk 2 above)
Comment (MarcelloPerathoner) [reply features/support/env.js:11]: The macOS builds fail randomly because of a race condition: see #7320 #7321. The build fails if `osrm-datastore` exits too early, not too late. Thus a longer timeout would not solve anything here.

And if `osrm-routed` dies for whatever reason, then a longer timeout would just slow down things because each scenario would take exactly timeout ms to fail.

OTOH the timeout was the reason the builds kept failing for such a long time: each time a build failed somebody just raised the timeout. Then, if the next CI run did by pure chance succeed, the problem was declared solved. Didn't you ever wonder how a totally absurd timeout of 60 seconds was reached?

I'm thinking of removing the timeout setting altogether. It induces people to fiddle with the parameters instead of finding the underlying cause. The default 5 sec is plenty.

File: docs/cucumber.md (hunk 3 above)
Comment (MarcelloPerathoner) [reply docs/cucumber.md]: fixed

File: features/support/cache.js (hunk 4 above)
Comment (MarcelloPerathoner) [reply features/support/cache.js]: fixed

File: features/support/env.js (hunk 2 above)
Comment (MarcelloPerathoner) [reply features/support/env.js:11]: Reinstated env var `CUCUMBER_TIMEOUT` with advice against using it.

**Comment by afarber** [comment]
Looks like your PR #7321 resolved the root cause - nice work.

I notice you've added back `setDefaultTimeout()` with `CUCUMBER_TIMEOUT` support, but since all the `CUCUMBER_TIMEOUT: 60000` entries were removed from the workflow, the env var is never set. It will always default to 5000ms, which is also Cucumber's built-in default.

You could simplify by removing `setDefaultTimeout()` again.

**Comment by MarcelloPerathoner** [comment]
Thanks. I put the timeout back in case somebody might want it badly, though I strongly advise against using it. Currently everything works fine with the default timeout.

File: features/options/datastore/datastore.feature [hunk 6]
```diff
@@ -1,33 +1,63 @@
-@datastore @options @help
+@datastore @options @help @isolated @no_datastore
```
Comment (TheMarex) [inline features/options/datastore/datastore.feature:1]: Hm I'm not so I follow: What does `@datastore` in conjunction with `@no_datastore` do?

File: features/step_definitions/data.js [hunk 7]
```diff
@@ -66,9 +61,7 @@ Given(/^the shortcuts$/, function (table, callback) {
 });
 
 Given(/^the node map$/, function (docstring, callback) {
-  const q = d3.queue();
```
Comment (TheMarex) [inline features/step_definitions/data.js:69]: Hm interesting - any idea why this used to be async?

File: features/support/route.js [hunk 8]
```diff
@@ -1,25 +1,43 @@
...
-    let uri;
-    if (service == 'timestamp') {
-      uri = [this.HOST, service].join('/');
-    } else {
-      uri = [this.HOST, service, 'v1', this.profile].join('/');
+  paramsToQuery(params) {
+    let query = '';
+    if (params.coordinates !== undefined) {
+      // FIXME this disables passing the output if its a default
+      // Remove after #2173 is fixed.
```
Comment (TheMarex) [inline features/support/route.js:15]: So actually that referenced issue _is_ fixed. Though honestly it may be fine to leave it implicitly as is.

File: features/testbot/alternative_loop.feature [hunk 9]
```diff
@@ -1,4 +1,4 @@
-@routing @testbot @alternative
+@routing @testbot @alternative @isolated @todo
```
Comment (TheMarex) [inline features/testbot/alternative_loop.feature:1]: Why the `todo` here?

File: features/testbot/load.feature [hunk 10]
```diff
@@ -1,5 +1,11 @@
-@routing @load @testbot
+@routing @load @testbot @todo @isolated @no_datastore
 Feature: Ways of loading data
+
+# TEST BROKEN: we don't support changing the load method in mid-run.
```
Comment (TheMarex) [inline features/testbot/load.feature:4]: If we don't start a new `osrm-routed` does this work though? The core here is I think the spring clean.

File: scripts/cucumber_test_matrix.sh [hunk 11]
```diff
@@ -2,17 +2,31 @@
 
 set -o errexit
 set -o pipefail
-set -o nounset
```
Comment (TheMarex) [inline scripts/cucumber_test_matrix.sh:5]: Left-over from debugging?

**Review by TheMarex — APPROVED** [review]
Looks great. 🙇 Tried it locally and while I'll miss the never ending row of green dots broken by the inevitable red `F` this is so nice. Massive amount of work, appreciate it. 🙌 Only minor questions / comments.

File: features/options/datastore/datastore.feature (hunk 6 above)
Comment (MarcelloPerathoner) [reply features/options/datastore/datastore.feature:1]: `@datastore` is a legacy tag, means: run all test concerning `osrm-datastore`. Those tests do ugly things like: `osrm-datastore --spring-clean`. So they cannot run while other tests are actually using the datastore. `@no_datastore` is a new tag, meaning: don't run if the selected load method is datastore. A bit confusing ...

File: features/step_definitions/data.js (hunk 7 above)
Comment (MarcelloPerathoner) [reply features/step_definitions/data.js:69]: Because it was easier to call it this way instead of thru a chain of callbacks?

File: features/testbot/alternative_loop.feature (hunk 9 above)
Comment (MarcelloPerathoner) [reply features/testbot/alternative_loop.feature:1]: That test must be rewritten. The result is unstable.

File: features/testbot/load.feature (hunk 10 above)
Comment (MarcelloPerathoner) [reply features/testbot/load.feature:4]: The logic for that test has been removed. While it may be possible to switch between `mmap` and `directly` I don't see the point. Most of those tests are duplicates.

File: scripts/cucumber_test_matrix.sh (hunk 11 above)
Comment (MarcelloPerathoner) [reply scripts/cucumber_test_matrix.sh:5]: `$GITHUB_STEP_SUMMARY` may be undefined.
