### PR TITLE
Fix macOS and Windows shared mem wait for detach

### LINKED ISSUE #7320: osrm-datastore on macOS and win do not wait for clients to switch
# Issue

`osrm-datastore` on macOS and Windows does not wait for other processes to detach from shared
memory before exiting. Instead it sleeps for 50ms and then boldly announces: 'All clients switched.' 

Symptoms:

- Cucumber tests fail randomly because queries are executed against old data when 50ms were not enough for clients to switch
- Cucumber tests do not run as fast as they could run when 50ms is plenty to switch

# Steps to reproduce

This happens with the new Parallel Cucumbers PR #7309 

# Specifications

Please provide details of your development environment.

- github CI 
- with PR #7309 applied

### PR DESCRIPTION
**Pull request by MarcelloPerathoner**
# Issue

Fixes #7320

On macOS and Windows `osrm-datastore` now correctly waits for other processes to detach from shared memory before exiting. Previous behaviour: `osrm-datastore` slept for 50ms and then boldly announced: 'All clients switched.'

This caused

- tests to fail randomly because queries were executed against old data, and
- tests to run slower than on linux.

## Tasklist

 - [ ] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [ ] add tests (see [testing documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/testing.md))
 - [ ] review
 - [ ] adjust for comments

## Requirements / Relations

Related to PR #7309

### CODE REVIEW

File: include/storage/shared_datatype.hpp [hunk 1]
```diff
@@ -192,12 +186,18 @@ class TarDataLayout final : public BaseDataLayout
     }
 };
 
+#if defined __key_t_defined
```
Comment (TheMarex) [inline include/storage/shared_datatype.hpp]: Compatibility issue with OSX? Maybe worth to add a small comment why we can't expect this to be present?

File: include/storage/shared_datatype.hpp [hunk 2]
```diff
@@ -207,7 +207,7 @@ struct SharedRegion
 
     char name[MAX_NAME_LENGTH + 1];
     std::uint64_t timestamp;
-    std::uint16_t shm_key = 0;
+    ShmKey shm_key = 0;
```
Comment (TheMarex) [inline include/storage/shared_datatype.hpp]: Just checking: We are not actually changing the size of this struct right? If so, I think this would be a breaking change since existing memory regions would be interpreted wrong.

File: include/storage/shared_memory.hpp [hunk 3]
```diff
@@ -48,12 +44,34 @@ inline std::filesystem::path getLockDir()
...
+{
+  public:
+    OSRMShmName(const ShmKey shm_key) { name = "osrm-" + std::to_string(shm_key); }
+    operator const char *() const noexcept { return name.c_str(); }
+
+  private:
+    std::string name;
 };
 
+using namespace boost::interprocess;
```
Comment (TheMarex) [inline include/storage/shared_memory.hpp]: Please do not use aliases like that in headers since it pollutes the namespace. it is fine to do this in cpp-files or function-local.

File: include/storage/shared_memory.hpp [hunk 4]
```diff
@@ -95,118 +109,85 @@ class SharedMemory
...
+            OSRMLockFile lock_file(shm_key);
+            xsi_key xsi_key(lock_file, shm_key);
+            xsi_shared_memory xsi(open_only, xsi_key);
+            while (true)
             {
-                auto error_code = errno;
-                throw util::exception("shmctl encountered an error: " + errorToMessage(error_code) +
-                                      SOURCE_REF);
+                ::shmid_ds xsi_ds;
+                if (::shmctl(xsi.get_shmid(), IPC_STAT, &xsi_ds) < 0)
```
Comment (TheMarex) [inline include/storage/shared_memory.hpp]: If I read this correctly, in the case of an error we swallow that and just return? Previously it would have thrown an exception.

File: include/storage/shared_memory.hpp [hunk 5]
```diff
@@ -95,118 +109,85 @@ class SharedMemory
...
-    boost::interprocess::xsi_shared_memory shm;
-    boost::interprocess::mapped_region region;
+  private:
+    xsi_shared_memory shm;
+    mapped_region region;
 };
 #else
-// Windows - specific code
+
+// POSIX shared mem
```
Comment (TheMarex) [inline include/storage/shared_memory.hpp]: I don't remember exactly why we used XSI over POSIX. Maybe issues with OSX at some point? To be honest we were originally planning to drop the whole hot-swapping thing in favor of mmap. The hotswap/shmem was conceived almost 15 years ago when the typical deployment process was "run it on a big server", not rolling deployments behind a load balancer.

Would have been nice for the 6.0 to clean this up but alas.

File: include/storage/shared_datatype.hpp (hunk 2 above)
Comment (MarcelloPerathoner) [reply include/storage/shared_datatype.hpp]: Good catch. ShmKey is 32 bits. If that is an issue, maybe I cannot use the shm key here but must use the id. Looking into it ...

File: include/storage/shared_memory.hpp (hunk 4 above)
Comment (MarcelloPerathoner) [reply include/storage/shared_memory.hpp]: But we are expecting an error here. The error being that the region is gone.

File: include/storage/shared_memory.hpp (hunk 3 above)
Comment (MarcelloPerathoner) [reply include/storage/shared_memory.hpp]: Moved stuff into .cpp file since there were no more templates.

File: include/storage/shared_datatype.hpp (hunk 2 above)
Comment (MarcelloPerathoner) [reply include/storage/shared_datatype.hpp]: Using the id now, which technically is also an int, but only the 8 lowest bits are used, so we can stuff it into a short. See `man 3 ftok`

File: include/storage/shared_datatype.hpp (hunk 1 above)
Comment (MarcelloPerathoner) [reply include/storage/shared_datatype.hpp]: key_t no longer used.

File: include/storage/shared_memory.hpp (hunk 4 above)
Comment (TheMarex) [reply include/storage/shared_memory.hpp]: But can we check for a precise error code in that case? There may be other reasons this call errors.

Comment (MarcelloPerathoner) [reply include/storage/shared_memory.hpp]: If we got there, the only plausible error that still can occur is: "EIDRM shmid points to a removed identifier". And that is exactly what we are waiting for to happen. I can test for this error and throw if any other error happens.

Comment (TheMarex) [reply include/storage/shared_memory.hpp]: IMHO it makes it a bit more clear that we are waiting for something specific to happen.
