### PR TITLE
Fix processing for data files with incorrect node references

### LINKED ISSUE #1552: segmentation fault while preparing
While running osrm-prepare I get a core dump.  

Running in debug gives me the following

/osrm/osrm7/BIKING$ osrm-prepare full.osrm   -p /home/ubuntu/osm-tools/osrm/profiles/bicycle.lua
[info] Input file: full.osrm
[info] Restrictions file: full.osrm.restrictions
[info] Profile: bicycle.lua
[info] Threads: 16
[debug] traffic_signal_penalty: 50
[info] Importing n = 383735439 nodes 
[info]  and 419012844 edges 
[info] Graph loaded ok and has 418560253 edges
[info] 0 restrictions, 188357 bollard nodes, 399407 traffic lights
[info] Generating edge-expanded graph representation
[info] merged 0 edges out of 806319922
[info] Removing graph geometry while preserving topology
osrm-prepare: /home/ubuntu/osm-tools/osrm/contractor/edge_based_graph_factory.cpp:382: void EdgeBasedGraphFactory::CompressGeometry(): Assertion `m_node_based_graph->GetEdgeData(forward_e1).nameID == m_node_based_graph->GetEdgeData(reverse_e1).nameID' failed.
Aborted (core dumped)

full.osrm was created by downloading about 50 pbf maps from geofabrik; converting them to .o5m; merging them with osm-convert and converting the result to pbf again. osrm-extract run without error.

Using the car and foot profile works fine.

This is on version 4.6.1

Any suggestions on how to solve this?

Thx!

### PR DESCRIPTION
**Pull request by TheMarex**
This fixes #1552

### CODE REVIEW

File: extractor/extraction_containers.cpp [hunk 1]
```diff
@@ -157,20 +157,41 @@ void ExtractionContainers::PrepareNodes()
...
     std::cout << "ok, after " << TIMER_SEC(sorting_nodes) << "s" << std::endl;
+
+    std::cout << "[extractor] Building node id map      ... " << std::flush;
+    TIMER_START(id_map);
+    external_to_internal_node_id_map.reserve(used_node_id_list.size());
+    auto node_iter = all_nodes_list.begin();
+    auto ref_iter = used_node_id_list.begin();
+    auto internal_id = 0u;
+    // compute the intersection of nodes that were referenced and nodes we actually have
+    while (node_iter != all_nodes_list.end() && ref_iter != used_node_id_list.end())
```
Comment (daniel-j-h) [inline extractor/extraction_containers.cpp]: Suggestion: hoist the end iterator outside of the loop to prevent the call on every iteration (as the compiler can prove it has no side-effects).
