### PR TITLE
Provides OSRM_ASSERT_WITH_LOC macros for asserting with location, resolves #3533

### LINKED ISSUE #3533: Assertions should log coordinates wherever possible
We've got lots of assertions all over the codebase, which is great.

What's not so great is that if we hit one when dealing with planet-sized data, it's often very difficult to track down what the cause was.

Many errors are location specific - they are caused due to specific network shape or properties.

We should create a wrapper to `BOOST_ASSERT`, called `OSRM_ASSERT_WITH_LOCATION`, where we pass in location data.  If the assertion is thrown, we should log the coordinates in addition to the failed assertion information.  This would (hopefully) make it much faster to track down datasets to reproduce the problem.

This is not always going to be possible, but it would massively speedup debugging for location-specific assertion failures.

### PR DESCRIPTION
**Pull request by daniel-j-h**
For #3533.

Assertions now log a clickable location url:

> [Location] http://www.openstreetmap.org/?mlat=52.5396&mlon=13.2954#map=19/52.5396/13.2954
> [assert] /tmp/osrm-backend/src/extractor/guidance/sliproad_handler.cpp:322 in: virtual osrm::extractor::guidance::Intersection osrm::extractor::guidance::SliproadHandler::operator()(NodeID, EdgeID, osrm::extractor::guidance::Intersection) const: false

## Tasklist
 - [x] review
 - [x] adjust for comments

### CODE REVIEW

**Comment by daniel-j-h** [comment]
Callsites need to be adapted where possible.

**Comment by oxidase** [comment]
@daniel-j-h would it make sense to catch assertion exceptions, log request part of URL and return error code in json instead of hard aborts?

**Comment by daniel-j-h** [comment]
Hm not sure about that - catching assertions from deep down the engine and going on in routed can be potentially problematic (think: corrupting internal state). Waiting on @danpat for what he had in mind anyway.

**Comment by oxidase** [comment]
@daniel-j-h 
 > corrupting internal state
Hrm, in the engine should not be an internal mutable state (think scaling), so failing one request should not influence others. At the moment an asserted request leads to the complete server process restart.

To have immutable data a compile-time guarantee of constness is required, eg datafacades must have the const qualifier. Anyway it deserves another PR that could add handling of asserts after finishing ongoing refactoring

**Comment by daniel-j-h** [comment]
Ah I see now what you mean - can you ticket this up so we don't forget about it.

File: include/util/assert.hpp [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+
+#include <boost/assert.hpp>
+
+// Enhances BOOST_ASSERT / BOOST_ASSERT_MSG with convenience location printing
+// - OSRM_ASSERT_WITH_LOC(cond, coordinate)
+// - OSRM_ASSERT_WITH_LOC_MSG(cond, coordinate, msg)
+
+#ifdef BOOST_ENABLE_ASSERT_HANDLER
+
+#define OSRM_ASSERT_WITH_LOC_MSG(cond, loc, msg)                                                   \
```
Comment (TheMarex) [inline include/util/assert.hpp]: Minor nitpick `OSRM_ASSERT` is a little bit shorter to type then `OSRM_ASSERT_WITH_LOC` and since we don't have `OSRM_ASSERT_WITHOUT_LOC` I don't think we need that extra piece of information. :-)

**Comment by daniel-j-h** [comment]
People - start using this! ;)
