### PR TITLE
Upgrade Boost to 1.70, fix inefficient connection handling

### LINKED ISSUE #6039: Requests to osrm-routed can block unexpectedly
A request to `osrm-routed` can be assigned to a thread which is currently busy processing another request, even when there are other threads/cores available. This unnecessarily delays the response, or as discussed in #6033 can make requests appear to hang when awaiting CPU intensive requests to finish.

## Example
Using the example from #6033, this can be reproduced on the France OSM extract.

Run `osrm-routed` with `--threads 4`

Make a request that takes 5-10 seconds to complete
```
curl "http://localhost:5000/match/v1/car/2.321508,48.786804;2.321818,48.786879;2.324377,48.788494;2.325426,48.789201;2.329152,48.792156;2.330842,48.793761;2.331307,48.794565;2.331179,48.797515;2.329416,48.800333;2.330373,48.803502;2.325861,48.805695;2.326538,48.808909;2.326434,48.809562;2.322967,48.810585;2.321333,48.81268;2.318826,48.813388;2.313959,48.814762;2.311833,48.816219;2.3085,48.817093;2.307014,48.818689;2.306723,48.819006;2.306392,48.819381;2.30451,48.821406;2.302983,48.823178;2.302381,48.824416;2.302295,48.824626;2.302189,48.8249;2.302258,48.825207;2.302356,48.825429;2.29527,48.826921;2.286896,48.829859;2.278856,48.833171;2.264636,48.834948;2.254055,48.840947;2.253821,48.848681;2.252192,48.850262;2.252257,48.851837;2.252987,48.853035;2.25459,48.85441;2.25607,48.855465;2.25607,48.855465;2.25607,48.855465;2.256419,48.855363;2.261688,48.858715;2.263236,48.859848;2.263947,48.860949;2.264302,48.861604;2.265494,48.863572;2.265515,48.863127;2.26597,48.86359;2.268027,48.865524;2.269227,48.867344;2.271596,48.869799;2.272392,48.870425;2.276031,48.874408;2.280104,48.877403;2.28296,48.881999;2.290968,48.887533;2.299986,48.890925;2.3003,48.891081;2.300603,48.891258;2.300776,48.891359;2.300923,48.891491;2.301007,48.891499;2.30109,48.89158;2.301092,48.891574;2.307688,48.895367;2.309913,48.896152;2.309947,48.896179?geometries=geojson&radiuses=5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;100;5;5;5;5;20;5;5;5;5;5;1000;200;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5"
```

Then some quicker requests, which at some point will block until the above request completes, and then continue:
```
while true
do
  curl "http://localhost:5000/match/v1/car/2.320208,48.702049;2.320521,48.702363;2.320843,48.702727;2.320874,48.702761;2.320874,48.702761;2.319644,48.701588" &>/dev/null
done
```
## Cause
The issue looks like a bug in Boost.Asio multithreaded networking stack.
`osrm-routed` server implementation is heavily influenced by the [HTTP server 3 example](https://www.boost.org/doc/libs/1_65_0/doc/html/boost_asio/examples/cpp03_examples.html) in the Boost.Asio docs.

Interestingly if we upgrade `osrm-routed` to look more like the [example](https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/example/cpp03/http/server3/connection.cpp) provided in the `1.70.0` release, the problem goes away.
The diff between them is a change in the way `strand` objects are used to prevent concurrent access from connection handles, which sounds related. It could be that the newer version has a fix for this issue.

### PR DESCRIPTION
**Pull request by mjjbell**
# Issue

A request to `osrm-routed` can be assigned to a thread which is currently busy processing another request, even when there
are other threads/cores available. This unnecessarily delays the response, and can make requests appear to hang when awaiting CPU intensive requests to finish.

See #6039 for details of how to reproduce the issue.

`osrm-routed` server implementation is heavily influenced by the [HTTP server 3 example](https://www.boost.org/doc/libs/1_65_0/doc/html/boost_asio/examples/cpp03_examples.html) in the
Boost.Asio docs. By upgrading to Boost 1.70 and updating the server connections to match the [example](https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/example/cpp03/http/server3/connection.cpp) provided in the 1.70
release, the problem is resolved.

The diff of the changes to the Boost.Asio stack are [vast](https://github.com/boostorg/asio/commit/59066d80b26e1d5b83b60d127ee17948d9ae9702), so it's difficult to identify the exact cause. However
the implementation change is to push the `strand` of execution into the socket (and timer) objects, which suggests it's
fixing the type of threading issue we are observing.

This PR therefore also bumps the Boost dependency to >= 1.70. Given this was released over two years ago and many people will have already been using this version as a dependency when building OSRM, I see this as low risk.

## Tasklist

 - [x] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [ ] add tests (see [testing documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/testing.md)
 - [ ] review
 - [ ] adjust for comments
 - [ ] cherry pick to release branch

## Requirements / Relations

Fixes #6039

### CODE REVIEW

File: src/server/connection.cpp [hunk 1]
```diff
@@ -17,8 +17,9 @@ namespace osrm
 namespace server
 {
 
-Connection::Connection(boost::asio::io_service &io_service, RequestHandler &handler)
-    : strand(io_service), TCP_socket(io_service), timer(io_service), request_handler(handler)
+Connection::Connection(boost::asio::io_context &io_context, RequestHandler &handler)
+    : strand(boost::asio::make_strand(io_context)), TCP_socket(strand), timer(strand),
```
Comment (mjjbell) [inline src/server/connection.cpp:21]: The important change is here. Instantiating the socket and timer with the strand.

File: src/server/connection.cpp [hunk 2]
```diff
@@ -27,12 +28,11 @@ boost::asio::ip::tcp::socket &Connection::socket() { return TCP_socket; }
 /// Start the first asynchronous operation for the connection.
 void Connection::start()
 {
-    TCP_socket.async_read_some(
-        boost::asio::buffer(incoming_data_buffer),
-        strand.wrap(boost::bind(&Connection::handle_read,
```
Comment (mjjbell) [inline src/server/connection.cpp:32]: This means we no longer need to explicitly use the strand in our connection event handlers.

File: CMakeLists.txt [hunk 3]
```diff
@@ -36,7 +36,7 @@ list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
 
 if(ENABLE_MASON)
   # versions in use
-  set(MASON_BOOST_VERSION "1.65.1")
+  set(MASON_BOOST_VERSION "1.73.0")
```
Comment (mjjbell) [inline CMakeLists.txt:39]: Upgrade Mason Boost to 1.73 as this is the first version >= 1.70 Mason provides that has all the libraries OSRM needs.

**Review by TheMarex — APPROVED** [review]
Thanks for digging. This code was literally c&p from the boost example mostly for testing and never really ran in our production system (HTTP went via the node bindings), I presume this is why this went unnoticed for so long.

**Comment by mjjbell** [comment]
Needs #6119 for CI to pass.

**Comment by hoerup** [comment]
Why not go with debian-bullseye and boost 1.74 for the docker image ?

**Comment by mjjbell** [comment]
> Why not go with debian-bullseye and boost 1.74 for the docker image ?

Hmm, it probably wasn't released when I started working on this. Will update.

**Comment by hoerup** [comment]
If you're updating boost requirement past 1.66 there is also the option of using boost.beast - but that is an entirely different task

**Comment by mjjbell** [comment]
> If you're updating boost requirement past 1.66 there is also the option of using boost.beast - but that is an entirely different task

I'll leave that for someone else :slightly_smiling_face: 

I'm going to include #6119 in this PR to get it over the line.

It upgrades Ubuntu CI to 20.04 and bumps the GCC and Node matrices to something more recent. Hopefully that's not  too controversial.

**Comment by nilsnolde** [comment]
I have little experience with cmake, but I could try my luck: is it possible to make 1.70 requirement optional for osrm-routed @mjjbell ? Very soon I’ll try to build some Python bindings for cross platform (and open source them based on pyosrm/cython), but that needs a manylinux compatible system, the freshest available is Debian 9 with boost 1.61. Of course it won’t need osrm-routed but glancing at the cmakelists.txt it’s not (yet) possible to exclude the server right? Would it be accepted to make the server component optional so one can safely downgrade the boost requirement?

**Comment by mjjbell** [comment]
Commented over in #6139, building the server could be optional.
