### PR TITLE
Fix math when we have equal latitudes.

### LINKED ISSUE #2243: Error during osrm-extract with OSRM 5.0
While setting up the v5 OSRM demo server, this error occurred during `osrm-extract` when processing the current planet file (see timestamps below for the exact file in use):

```
[Sun, 10 Apr 2016 00:47:32 GMT] [2016-04-09-203750] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[Sun, 10 Apr 2016 00:47:32 GMT] [2016-04-09-203750] [info] Generated 617517573 nodes in edge-expanded graph
[Sun, 10 Apr 2016 00:47:32 GMT] [2016-04-09-203750] [info] generating edge-expanded edges
[warn] bad numeric conversion: positive overflow
```

/cc @TheMarex @MoKob

### PR DESCRIPTION
**Pull request by danpat**
In circleCenter, Don't use the slope when two coordinates are at the
same latitude.

This fixes #2243

### CODE REVIEW

File: src/extractor/edge_based_graph_factory.cpp [hunk 1]
```diff
@@ -1,13 +1,13 @@
...
 #include "util/coordinate.hpp"
 #include "util/coordinate_calculation.hpp"
-#include "util/percent.hpp"
+#include "util/exception.hpp"
 #include "util/integer_range.hpp"
 #include "util/lua_util.hpp"
+#include "util/percent.hpp"
 #include "util/simple_logger.hpp"
 #include "util/timing_util.hpp"
-#include "util/exception.hpp"
```
Comment (MoKob) [inline src/extractor/edge_based_graph_factory.cpp]: all formatting (sort includes)

**Comment by TheMarex** [comment]
Good work @danpat and @MoKob :+1:
