### PR TITLE
Incorrect error message when unable to snap all input coordinates

### LINKED ISSUE #5845: Incorrect error message when querying a table service
Before calculating routes, I try to check the reachability (no “disconnected” road segments) of the destinations. 
I want to do this through a table query - from depot to each item.

To test it, I took a sample query from the documentation and added an unreachable point to it and added a "radiuses" parameter.
[http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219;44.0086,30.7672?sources=0&radiuses=300;300;300;300](http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219;44.0086,30.7672?sources=0&radiuses=300;300;300;300)

Query result: 
`{"message":"Could not find a matching segment for coordinate 3","code":"NoSegment"}`

OK. I change the source point number to 2
[http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219;44.0086,30.7672?sources=2&radiuses=300;300;300;300](http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219;44.0086,30.7672?sources=2&radiuses=300;300;300;300)

Query result: 
`{"message":"Could not find a matching segment for coordinate 3","code":"NoSegment"}`

OK. I change the order of the points and put the unreachable point first.
[http://router.project-osrm.org/table/v1/driving/44.0086,30.7672;13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?sources=0&radiuses=300;300;300;300](http://router.project-osrm.org/table/v1/driving/44.0086,30.7672;13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?sources=0&radiuses=300;300;300;300)

Query result: 
`{"message":"Could not find a matching segment for coordinate 3","code":"NoSegment"}`

OK. I change the source point number to 1
[http://router.project-osrm.org/table/v1/driving/44.0086,30.7672;13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?sources=1&radiuses=300;300;300;300](http://router.project-osrm.org/table/v1/driving/44.0086,30.7672;13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?sources=1&radiuses=300;300;300;300)

Query result: 
`{"message":"Could not find a matching segment for coordinate 3","code":"NoSegment"}`

I would like to get exactly the index of the point (or points) to which the route cannot be laid. But the response from the server is the same every time, and it is impossible to understand what the destination is incorrect.

It would be ideal to have an array of such points in the server's response.

It would be possible to make separate routing requests for each depot-client pair, but I have 400-500 destinations each time.
Is there another way to find unreachable destinations with a single query?

### PR DESCRIPTION
**Pull request by fofanov**
# Issue
Fixes #5845 

In cases where we are unable to find a phantom node for an input
coordinate, we return an error indicating which coordinate failed.

This would always refer to the coordinate with index equal to the
number of valid phantom nodes found.

We fix this by instead returning the first index for which a
phantom node could not be found.

## Tasklist

 - [x] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))
 - [x] add tests (see [testing documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/testing.md)
 - [ ] review
 - [ ] adjust for comments
 - [ ] cherry pick to release branch

### CODE REVIEW

File: include/engine/plugins/plugin_base.hpp [hunk 1]
```diff
@@ -371,6 +371,23 @@ class BasePlugin
         }
         return phantom_node_pairs;
     }
+
+    std::string MissingPhantomErrorMessage(const std::vector<PhantomNodePair> &phantom_nodes,
+                                           const std::vector<util::Coordinate> &coordinates) const
+    {
+        BOOST_ASSERT(phantom_nodes.size() < coordinates.size());
+        size_t missing_index = phantom_nodes.size();
+        for (size_t i : util::irange<size_t>(0, phantom_nodes.size()))
```
Comment (danpat) [inline include/engine/plugins/plugin_base.hpp:380]: Suggestion: I think this could be done with `std::mismatch`, which I think helps clarify intent a bit.

```cpp
auto mismatch = std::mismatch(phantom_nodes.begin(), phantom_nodes.end(), 
                              coordinates.begin(), coordinates.end(),
                              [](const auto &phantom_node, const auto &coordinate) {
                                return phantom_node.first.input_location == coordinate;
                              });
std::size_t missing_index = std::distance(phantom_nodes.begin(), mismatch.first);
```

Comment (fofanov) [reply include/engine/plugins/plugin_base.hpp]: Nice. Yes, a lot clearer.

**Review by danpat — APPROVED** [review]
